songify_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from main.views import AllSongsPage
from main.views import SearchPage
from main.views import main_page
from main.views import RegisterPage
from main.views import LogoutPage
from main.views import LoginPage
from main.views import AuthorPage
from main.views import AllAuthorsPage
from main.views import SongPage

from django.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', SearchPage.as_view(), name='SearchPage'),
    path('all-songs/', AllSongsPage.as_view(), name='AllSongs'),
    path('', main_page, name='MainPage'),


    path("register/", RegisterPage.as_view(), name='RegisterPage'),
    path("login/", LoginPage.as_view(), name='LoginPage'),
    path('authors/<slug:slug>', AuthorPage.as_view(), name='author_page'),
    path('authors/', AllAuthorsPage.as_view(), name='all_authors'),
    path("logout/", LogoutPage.as_view(), name='LogoutPage'),
    path("play/<slug:slug>", SongPage.as_view(), name='song_page'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models
from io import BytesIO
from PIL import Image
from django.core.files import File
from django.utils.crypto import get_random_string
def compress(image):
    im = Image.open(image)
    im_io = BytesIO()
    im.save(im_io, 'JPEG',optimize=True, quality="web_medium")
    new_image = File(im_io, name=image.name)
    return new_image

class Category(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True, null=True)
    country = models.CharField(max_length=8, blank=True)
    slug = models.SlugField(max_length=32)
    profile_picture = models.ImageField(upload_to='author_profile_picture_images/')
    profile_background = models.ImageField(upload_to='author_profile_background_images/')

    def save(self, *args, **kwargs):
        original_size_profile_picture = self.profile_picture.size
        original_size_profile_background = self.profile_background.size

        compressed_profile_picture = compress(self.profile_picture)
        compressed_profile_background = compress(self.profile_background)

        compressed_size_profile_picture = compressed_profile_picture.size
        compressed_size_profile_background = compressed_profile_background.size

        self.profile_picture = compressed_profile_picture
        self.profile_background = compressed_profile_background
        print(f'Compression ended [{self.profile_picture.name}][{original_size_profile_picture}][{compressed_size_profile_picture}][{compressed_size_profile_picture-original_size_profile_picture}]')
        print(f'Compression ended [{self.profile_background.name}][{original_size_profile_background}][{compressed_size_profile_background}][{compressed_size_profile_background-original_size_profile_background}]')
        super().save(*args, **kwargs)
    def __str__(self):
        return self.name


def file_path(instance, filename):
     return f'{instance.title}/{filename}'

class Song(models.Model):
    title = models.CharField(max_length=64)
    slug = models.SlugField(max_length=8, blank=True)
    author = models.ManyToManyField(Author)
    category = models.ManyToManyField(Category)
    number_of_plays = models.PositiveIntegerField(default=0)
    cover_image = models.ImageField(upload_to=file_path)
    music_file = models.FileField(upload_to=file_path)
    lyrics = models.TextField()

    def save(self, *args, **kwargs):
        original_size = self.cover_image.size
        compressed_cover_image = compress(self.cover_image)
        compressed_size = compressed_cover_image.size
        self.cover_image = compressed_cover_image
        if not self.slug:
            self.slug = get_random_string(length=8)
        print(f'Compression ended [{self.cover_image.name}][{original_size}][{compressed_size}][{compressed_size-original_size}]')
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.author.name} - {self.title}"

    class Meta:
        get_latest_by = "id"

class Playlist(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField()
    slug = models.SlugField(max_length=32)
    playlist_image = models.ImageField(upload_to='playlist_cover_images/')
    playlist_background = models.ImageField(upload_to='playlist_background_images/')
    songs = models.ManyToManyField(Song)

    def __str__(self):
        return self.name

main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
import django.forms.widgets as widgets


class UserRegisterForm(UserCreationForm):
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'type': 'password'}),
        required=True,
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'type': 'password'}),
        required=True,
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': widgets.TextInput(attrs={'class': 'form-control'}, ),
            'email': widgets.EmailInput(attrs={'class': 'form-control'}),
        }
        error_messages = {
            'username': {
                'unique': 'This username exists!',
                'required': 'Enter username!'
            },
            'password2': {
                'password_mismatch': 'Passwords are not identical!',
            },
            'email': {
                'unique': 'Ten adres email jest już używany!'
            }

        }


class AuthForm(AuthenticationForm):
    username = forms.CharField(
        widget=widgets.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter username'}))
    password = forms.CharField(
        widget=widgets.PasswordInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter password'}))

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView, ListView, RedirectView
from main.models import Song, Author, Playlist
from random import choice, choices, sample
from django.views.generic import CreateView
from .forms import UserRegisterForm
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import LogoutView, LoginView
from main.forms import AuthForm
from django.contrib.auth.mixins import LoginRequiredMixin


class SearchPage(TemplateView):
    template_name = 'main/search_page.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        # Pobieranie parametru q z adresu url (np: songify.com/search?q=)
        query = request.GET.get('q', 'all')
        context['songs_search_result'] = Song.objects.filter(title__contains=query).all()
        context['authors_search_result'] = Author.objects.filter(name__contains=query).all()
        context['playlists_search_result'] = Playlist.objects.filter(name__contains=query).all()
        return self.render_to_response(context)


class RegisterPage(SuccessMessageMixin, CreateView):
    template_name = 'registration/register.html'
    success_url = reverse_lazy('LoginPage')
    form_class = UserRegisterForm
    success_message = "Zarejestrowano pomyślnie!"


class LoginPage(SuccessMessageMixin, LoginView):
    template_name = 'registration/login.html'
    authentication_form = AuthForm


class LogoutPage(SuccessMessageMixin, LogoutView):
    success_message = 'Zostałeś wylogowany'
    next_page = 'LoginPage'


MOTD_TEXT = [
    'Songify - to co lubisz, tak jak chcesz',
    'Songify - zabierz ze sobą',
    'Songify - twoja lista',
    'Songify - tak jak lubisz',
    'Songify - muzyka dla ciebie',
    'Songify - twoja muzyka',
    'Songify - twoje utwory',
    'Songify - słuchaj muzyki',
]
NEW_SONG_LABEL = [
    'Check out my new song - ',
    'New release - ',
    'Latest release - '
]

def main_page(request):
    context_dir = {
        'new_song_label': choice(NEW_SONG_LABEL),
        'new_song': Song.objects.latest(),
        'choosen_for_you': sample(list(Song.objects.all()), 6),
        'discover_new_artists': sample(list(Author.objects.all()), 5),
        'top_songs': Song.objects.order_by('-number_of_plays').all(),
        'motd': choice(MOTD_TEXT),
    }
    return render(request, template_name='main/main_page.html', context=context_dir)


class AuthorPage(DetailView):
    model = Author
    template_name = 'main/author_page.html'
    slug_field = 'slug'
    context_object_name = 'author'


class AllAuthorsPage(ListView):
    model = Author
    template_name = 'main/all_authors_page.html'
    context_object_name = 'list'


class AllSongsPage(ListView):
    model = Song
    template_name = 'main/all_songs_page.html'
    context_object_name = 'list'

class SongPage(DetailView):
    model = Song
    template_name = 'main/song_page.html'
    slug_field = 'slug'
    context_object_name = 'song'

    def get_object(self):
        obj = super().get_object()
        obj.number_of_plays += 1
        obj.save(update_fields=['number_of_plays'])
        return obj
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['up_next'] = sample(list(Song.objects.all()), 5)
        return self.render_to_response(context)

templates/main/all_authors_page.html
{% extends 'main/root_template.html' %}
{% load static %}

{% block page_title %}
    <title>{{ motd }}</title>
{% endblock %}

{% block page_content %}
    {% include 'main/includes/navbar.html' %}
    <div class="container mt-2 rounded-4 bg-dark text-white">
        <div class="row p-5">
            <p class="display-5">Wykonawcy</p>
            {% include 'main/includes/author-list.html' with authors=list %}
        </div>
    </div>



    {#< ! ╌  test ╌>#}
    {#        <div class="text-light bg-dark">#}
    {#            <div class="container mt-5">#}
    {#                <div class="row mt-12 text-white gy-5">#}
    {#                    <p class="display-3">Najnowszy utwór</p>#}
    {#    #}
    {#                    {% for song in top_songs %}#}
    {#                        <div class="card border-0 text-center mx-6 my-6 text-light no-padding bg-dark" style="max-width: 11rem;">#}
    {#                            <img src="{{ song.image.url }}" class="card-img-top">#}
    {#                            <div class="card-body">#}
    {#                                <h5 class="card-title">{{ song.title }}</h5>#}
    {#    #}
    {#                                <a class="text-reset text-decoration-none" href="#"><p class="card-text">{{ song.author }}</p></a>#}
    {#                                <a href="#" class="btn btn-primary">Słuchaj</a>#}
    {#                        <a class="text-reset text-decoration-none" href="{% url 'author_page' slug=song.author.slug %}"><p class="card-text">{{ song.author }}</p></a>#}
    {#                        <a href="{% url 'song_page' slug=song.slug %}" class="btn btn-primary">Słuchaj</a>#}
    {#                            </div>#}
    {#                        </div>#}
    {#                    {% endfor %}#}
    {#                </div>#}
    {#            </div>#}
    {#        </div>#}
    {#        <div class="container">#}
    {#          <div class="row">#}
    {#            <div class="col-lg-4 col-md-12">#}
    {#                test#}
    {#            </div>#}
    {#    #}
    {#            <div class="col-lg-4 col-md-6">#}
    {#                test#}
    {#            </div>#}
    {#    #}
    {#            <div class="col-lg-4 col-md-6">#}
    {#                test#}
    {#            </div>#}
    {#          </div>#}
    {#    </div>#}
    {#< ! ╌  end test ╌>#}


{% endblock %}

templates/main/all_songs_page.html
{% extends 'main/root_template.html' %}
{% load static %}

{% block page_title %}
    <title>{{ motd }}</title>
{% endblock %}

{% block page_content %}
    {% include 'main/includes/navbar.html' %}
    <div class="container mt-2 rounded-4 bg-dark text-white class_list" style="margin-top: 80px">
        <p class="display-5">Wszystkie utwory</p>


            {% for song in list %}


                <div class="row row_list">
                    <div class="col-sm-1">
                        <img src="{{ song.cover_image.url }}" class="img-fluid img-thumbnail">
                    </div>
                    <div class="col-sm-3 d-flex align-items-center">
                        <a href="{% url 'song_page' slug=song.slug  %}" class="hover-3">{{ song.title }}</a>
                    </div>
                    <div class="col-sm-6 d-flex align-items-center">
                                {% for author in song.author.all %}
                                    <a href="{% url 'author_page' slug=author.slug  %}" class="hover-3">{{ author.name }}&nbsp;|&nbsp;</a>
                                {% endfor %}
                    </div>
                    <div class="col-sm-2 d-flex align-items-center">
                        <i class="bi bi-folder-plus"></i>
                    </div>
                </div>

            {% endfor %}

        </div>



    {#< ! ╌  test ╌>#}
    {#        <div class="text-light bg-dark">#}
    {#            <div class="container mt-5">#}
    {#                <div class="row mt-12 text-white gy-5">#}
    {#                    <p class="display-3">Najnowszy utwór</p>#}
    {#    #}
    {#                    {% for song in top_songs %}#}
    {#                        <div class="card border-0 text-center mx-6 my-6 text-light no-padding bg-dark" style="max-width: 11rem;">#}
    {#                            <img src="{{ song.image.url }}" class="card-img-top">#}
    {#                            <div class="card-body">#}
    {#                                <h5 class="card-title">{{ song.title }}</h5>#}
    {#    #}
    {#                                <a class="text-reset text-decoration-none" href="#"><p class="card-text">{{ song.author }}</p></a>#}
    {#                                <a href="#" class="btn btn-primary">Słuchaj</a>#}
    {#                        <a class="text-reset text-decoration-none" href="{% url 'author_page' slug=song.author.slug %}"><p class="card-text">{{ song.author }}</p></a>#}
    {#                        <a href="{% url 'song_page' slug=song.slug %}" class="btn btn-primary">Słuchaj</a>#}
    {#                            </div>#}
    {#                        </div>#}
    {#                    {% endfor %}#}
    {#                </div>#}
    {#            </div>#}
    {#        </div>#}
    {#        <div class="container">#}
    {#          <div class="row">#}
    {#            <div class="col-lg-4 col-md-12">#}
    {#                test#}
    {#            </div>#}
    {#    #}
    {#            <div class="col-lg-4 col-md-6">#}
    {#                test#}
    {#            </div>#}
    {#    #}
    {#            <div class="col-lg-4 col-md-6">#}
    {#                test#}
    {#            </div>#}
    {#          </div>#}
    {#    </div>#}
    {#< ! ╌  end test ╌>#}


{% endblock %}

templates/main/author_page.html
{% extends 'main/root_template.html' %}
{% block page_title %}
    <title>{{ author.name }} - profile</title>
{% endblock %}
{% block page_content %}
    <div class="container-fluid text-light bg-dark p-0"
         style="background-image: url({{ author.profile_background.url }}); background-size: cover; background-position: center">
        <div class="container-fluid p-5" style="backdrop-filter: blur(5px) brightness(50%)">
            <div class="container">
                <div class="row justify-content-center align-items-center gx-5 gy-3">
                    <div class="col-md-4 text-center">
                        <img src="{{ author.profile_picture.url }}" class="img-fluid shadow rounded-50">
                    </div>
                    <div class="col-md-8">
                        <p class="fs-5 mt-2 lh-1"><i class="bi bi-check-circle-fill"></i> Verified author</p>
                        <h1 class="display-1 fw-semibold">{{ author.name }}</h1>
                        {% if author.country %}
                            <p class="fs-5">Country <span class="fi fi-{{ author.country }}"></span></p>
                        {% endif %}
                        <p class="fs-3">{{ author.description }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-5">
        <p class="fs-1">{{ author.name }} songs - {{ author.song_set.count }}</p>
        <div class="row rounded-3 d-flex justify-content-start g-2">
            {% for song in author.song_set.all %}
                {% include 'main/includes/song-small-card.html' %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/main/main_page.html
{% extends 'main/root_template.html' %}
{% load static %}

{% block page_title %}
    <title>{{ motd }}</title>
{% endblock %}

{% block page_content %}
    <a href="{% url 'song_page' slug=new_song.slug %}" class="text-reset text-decoration-none">
        <div class="container-fluid text-light bg-dark p-0"
             style="background-image: url({{ new_song.author.first.profile_background.url }}); background-size: cover; background-position: center">
            <div class="container-fluid p-5" style="backdrop-filter: blur(5px) brightness(50%)">
                <div class="container">
                    <!-- New song message -->
                    <div class="row align-items-center">
                        <span class="fs-3"><img src="{{ new_song.author.first.profile_picture.url }}"
                                                class="rounded-50 me-2 shadow"
                                                style="max-height: 6rem; max-width: 6rem">{{ new_song_label }}{{ new_song.title }}!</span>
                    </div>
                    <!-- New song image and title -->
                    <div class="row gy-2 mt-3 align-items-center">
                        <div class="col-md-3">
                            <img src="{{ new_song.cover_image.url }}" class="img-fluid shadow">
                        </div>
                        <div class="col-md-9">
                            <p class="display-3 fw-semibold lh-1">
                                {{ new_song.title }}
                            </p>
                            <p class="fs-4 fw-semibold lh-1">
                                {{ new_song.author.first }}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </a>
    <!-- Chosen for you section -->
    <div class="container mt-5">
        <div class="row">
            <p class="display-4 fw-semibold">Chosen for you</p>
        </div>
        <div class="row flex-row flex-nowrap overflow-auto">
            {% for song in choosen_for_you %}
                {% include 'main/includes/song-small-card.html' %}
            {% endfor %}
        </div>
    </div>
    <!-- Discover artists section -->
    <div class="container mt-5">
        <div class="row">
            <p class="display-4 fw-semibold">Discover artists</p>
        </div>
        <div class="row flex-row flex-nowrap overflow-auto" style="touch-action: pan-x;">
            {% for author in discover_new_artists %}
                {% include 'main/includes/author-small-card.html' %}
            {% endfor %}
        </div>
    </div>
    <!-- Top songs section -->
    <div class="container mt-5">
        <div class="row gy-2">
            <div class="col-lg-6">
                <p class="display-4 fw-semibold">Top songs on Songify</p>
                {% include 'main/includes/song-list.html' with songs=top_songs %}
            </div>
        </div>
    </div>
{% endblock %}
{% block page_custom_js %}
    <script>
        function search() {
            var query = document.getElementById('search_bar').value
            console.log(`/search/?q=${query}`)
            window.location.href = `/search/?q=${query}`;
        }
    </script>
{% endblock %}

templates/main/root_template.html
{% load static %}
<!doctype html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block page_title %}

    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lipis/flag-icons@6.6.6/css/flag-icons.min.css">
    <link rel="stylesheet" href="{% static 'main/css/custom.css' %}">

</head>
<body class="text-white" style="background-color: black">
{% include 'main/includes/navbar.html' %}
{% block page_content %}

{% endblock %}
{% include 'main/includes/footer.html' %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
{% block page_custom_js %}

{% endblock %}
</body>
</html>

templates/main/root_template_no_footer.html
{% load static %}
<!doctype html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block page_title %}

    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lipis/flag-icons@6.6.6/css/flag-icons.min.css">
    <link rel="stylesheet" href="{% static 'main/css/custom.css' %}">

</head>
<body class="text-white" style="background-color: black">
{% block page_content %}

{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
<script src="https://vjs.zencdn.net/7.20.3/video.min.js"></script>
{% block page_custom_js %}

{% endblock %}
</body>
</html>

templates/main/search_page.html
{% extends 'main/root_template.html' %}
{% load static %}
{% block page_content %}
    {% include 'main/includes/navbar.html' %}
    <div class="container mt-5 p-5 rounded-4 bg-dark text-white">
        <h1 class="display-2">Wyniki wyszukiwania</h1>
        <div class="row">
            <p class="display-4 mt-5">Utwory</p>
            {% include 'main/includes/song-list.html' with songs=songs_search_result %}
        </div>
        <p class="display-4 mt-5">Artyści</p>
        <div class="row flex-row flex-nowrap overflow-auto"
             style="touch-action: pan-x;">
            {% for author in authors_search_result %}
                <div class="cardborder-0 rounded-2 text-white p-0 m-2 shadow" style="max-width: 18rem; background-color: #323539">
                    <img src="{{ author.profile_picture.url }}" class="card-img-top rounded-50 p-4" alt="...">
                    <div class="card-body text-center pb-2">
                        <h5 class="card-title">{{ author.name }}</h5>
                        <p class="card-text">Wykonawca</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block page_custom_js %}
{% endblock %}